=== VioletKimera/Examen_Marcas/11/personajes.dtd
<!ELEMENT personajes (personaje+)>

<!ELEMENT personaje (imagen, perfil+)>
<!ATTLIST personaje id ID #REQUIRED>
<!ATTLIST personaje alias CDATA #IMPLIED>
<!ATTLIST personaje rareza CDATA "raro">

<!ELEMENT imagen (#PCDATA)>

<!ELEMENT perfil (nombre, especie, poder, localizacion, incidente, descripcion, audio, tituloAudio)>
<!ATTLIST perfil id ID #REQUIRED>
<!ATTLIST perfil alias CDATA #IMPLIED>
<!ATTLIST perfil rareza CDATA "raro">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT especie (#PCDATA)>
<!ELEMENT poder (#PCDATA)>
<!ELEMENT localizacion (#PCDATA)>
<!ELEMENT descripcion (p+)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT audio (#PCDATA)>
<!ELEMENT tituloAudio (#PCDATA)>

=== VioletKimera/Examen_Marcas/17/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/keiki.png</imagen>
    
    <perfil id="keiki" alias="Diosa escultora" rareza="epica">
      <nombre>Keiki Haniyasushin</nombre>
      <especie>Diosa</especie>
      <poder>Crear ídolos</poder>
      <localizacion>Jardín espiritual de las bestias</localizacion>
      <descripcion>
      <p>En el Reino Animal, donde los más fuertes reinan y los débiles se sometan, los espíritus humanos no podían competir con la fuerza de los espíritus de las bestias.
      Pero los espíritus humanos buscaron una forma de liberarse del control de las bestias rezando por un salvador. Tras eso, Keiki fue convocada y les dijo que depositaran toda su fe en los ídolos que ella creaba.</p>
      <p>Sin embargo, nunca pensó que a los semejantes de los espíritus animales se les ocurriría un plan para traer a un humano de la superficie para destruir a sus ídolos.</p>
      <p>"Construiste todo este plan, y ahora huyes ante el enemigo... es el colmo de la idiotez. No pienses ni por un segundo que te dejaré escapar después de que hayas pisado mi territorio sagrado. Destruiré tu cuerpo de carne y te construiré de nuevo usando tierra y agua. Serás un ídolo sin un solo defecto".</p>
     
      </descripcion>
      <audio>audio/keiki.opus</audio>
      <tituloAudio>Entrust this World to Idols ~ Idolatrize World</tituloAudio>
   </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/15/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/hecatia.png</imagen>
    
    <perfil id="hecatia" alias="Diosa del infierno" rareza="legendaria">
      <nombre>Hecatia Lapislazuli</nombre>
      <especie>Diosa</especie>
      <poder>Tener tres cuerpos</poder>
      <localizacion>Infierno </localizacion>
      <descripcion>
      <p>Una diosa misteriosa que gobierna los infiernos de la luna, la Tierra y otros mundos. Posee un cuerpo separado en cada uno de los mundos y puede actuar independientemente con cada uno de ellos.</p>
      <p> Ya que la Luna, la Tierra y los demás mundos tienen su propio Infierno, y su alma central reside en el Infierno,
es una diosa bastante problemática contra la que no se le puede tomar represalias fácilmente si se le ve como una enemiga. </p>
      <p>Tiene un deseo inquebrantable de libertad personal y no le gustan los seres autoritarios de cualquier tipo (algo que coincide con su apariencia "no convencional"). Concretamente tiene un fuerte odio hacia los lunarians, ya que los considera antítesis de su ideología.</p>
     
      </descripcion>
      <audio>audio/hecatia.opus</audio>
      <tituloAudio>Pandemonic Planet</tituloAudio>
    </perfil>
    <perfil id="clownpiece" alias="Hada del infierno" rareza="atipica">
      <nombre>Clownpiece</nombre>
      <especie>Lampad</especie>
      <poder>Generar locura en las personas</poder>
      <localizacion>Infierno - Santuario Hakurei</localizacion>
      <descripcion>
      <p>Las hadas se pueden encontrar en casi cualquier lugar, el infierno no es una excepción, aunque a estas se les suele llamar Lampads.</p>
      <p> Es una de las tantas subordinadas de Hecatia, quién la ha instruido para vivir en Gensokyo y actualmente vive bajo el Santuario de Hakurei en una réplica del infierno que hizo para sí misma. </p>
      <p>La llama de su antorcha es capaz de afectar a la fuerza de vidam tanto para bien como para mal, esta antorcha arde con la fuerza vital de quienes cayeron al infierno. </p>
     
      </descripcion>
      <audio>audio/clownpiece.opus</audio>
      <tituloAudio>Pierrot of the Star ~ Spangled Banner</tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/8/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/kaguya.png</imagen>
    
    <perfil id="Eirin" alias="Cerebro de la Luna" rareza="Atipica">
      <nombre>Eirin Yagokoro</nombre>
      <especie>Lunarian (Diosa)</especie>
      <poder>Creación de medicinas y drogas</poder>
      <localizacion>Eientei</localizacion>
      <descripcion>
        <p>La familia Yagokoro es conocida por estar llena de genios medicinales que han estado viviendo en la luna durante mucho tiempo. Incluso entre ellos, Eirin es excepcionalmente inteligente, y sobre todo es mucho más inteligente que cualquier humano.   </p>
        <p>Hace mucho tiempo, Eirin formaba parte de un grupo de mensajeros enviados a la tierra para traer de vuelta a la princesa Kaguya hacia la luna, pero por alguna razón ayudó a Kaguya a matar a todos los demás mensajeros. 
        Para asegurarse de que los terrícolas que vivían con Kaguya en ese entonces permanecieran en silencio, los sobornó con el Elixsit Hourai. Un elixir con el poder de hacer a la gente inmortal. Sin embargo, ninguno de esos terrícolas consumió el elixir y murieron poco después.  </p>
      <p> Actualmente vive en el Eientei junto a la Princesa Kaguya, creando medicinas y elixires para los humanos y yokai de Gensokyo.</p>
      </descripcion>
      <audio>audio/eirin.mp3</audio>
      <tituloAudio>Gensokyo Millennium ~ History of the Moon</tituloAudio>
    </perfil>
    
    <perfil id="Kaguya" alias="Princesa Eterna" rareza="Legendaria">
      <nombre>Kaguya Houraisan</nombre>
      <especie>Lunarian</especie>
      <poder>Manipular la eternidad</poder>
      <localizacion>Eientei</localizacion>
      <descripcion>
        <p>Nació en la casa real de la luna y fue tratada con el máximo cuidado como una princesa. Por eso, se hizo muy egoísta. Pero un escándalo le cambió la vida. Hizo que Eirin hiciera el Elixir Hourai(-una medicina prohibida) por interés propio y la consumió.</p>
        <p> Kaguya fue ejecutada por ello, pero gracias al poder de la eternidad otorgado por el Elixir, resucitó inmediatamente. Como no podía morir, fue exiliada a la Tierra y obligada a vivir entre sucios humanos.  </p>
     <p>Unos años después, se le permitió volver a la luna, pero se había apegado a las personas con las que vivía y prefería la vida en la Tierra, que era mucho más emocional que la vida que tenía en la luna.</p>
      <p>Ha pasado mucho, mucho tiempo desde entonces.</p>
      </descripcion>
      <audio>audio/kaguya.mp3</audio>
      <tituloAudio>Flight of the Bamboo Cutter ~ Lunatic Princess</tituloAudio>
    </perfil>
    
  </personaje>
</personajes>
