=== VioletKimera/Examen_Marcas/11/personajes.dtd
<!ELEMENT personajes (personaje+)>

<!ELEMENT personaje (imagen, perfil+)>
<!ATTLIST personaje id ID #REQUIRED>
<!ATTLIST personaje alias CDATA #IMPLIED>
<!ATTLIST personaje rareza CDATA "raro">

<!ELEMENT imagen (#PCDATA)>

<!ELEMENT perfil (nombre, especie, poder, localizacion, incidente, descripcion, audio, tituloAudio)>
<!ATTLIST perfil id ID #REQUIRED>
<!ATTLIST perfil alias CDATA #IMPLIED>
<!ATTLIST perfil rareza CDATA "raro">

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT especie (#PCDATA)>
<!ELEMENT poder (#PCDATA)>
<!ELEMENT localizacion (#PCDATA)>
<!ELEMENT descripcion (p+)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT audio (#PCDATA)>
<!ELEMENT tituloAudio (#PCDATA)>

=== VioletKimera/Examen_Marcas/12/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/byakuren.png</imagen>
    
    <perfil id="byakuren" alias="La gran maga sellada" rareza="Legendaria">
      <nombre>Byakuren Hijiri</nombre>
      <especie>Maga</especie>
      <poder>Aumento de poder físico</poder>
      <localizacion>Antiguo infierno de los fuegos ardientes</localizacion>
      <descripcion>
      <p>"Ahora mismo estás poseído por un espíritu maligno.
Tienes que resistirte, o morirás".</p>

<p>La cabeza del Templo Myouren, un templo budista que acepta incluso youkai.</p>
      <p>En sus últimos años estudió el camino del Dharma, pero cuándo su hermano murió, empezó a tener un terrible miedo a la muerte. Para salvarse de su propia muerte, aprendió el poder del rejuvenecimiento. Pero en lugar de hacerlo por forma del Dharma, obtuvo este poder del youjutsu, una especie de brujería.</p>
        <p> Al principio iba a servir a sus propios deseos, pero como se enteró del lamentable pasado de los youkai, comenzó a pensar que necesitaba hacer algo para ayudarlos.</p>
    <p>Actualmente es la suma sacerdotisa en el Templo de Myouren, donde su objetivo principal es llevar la paz tanto a los humanos como a los youkai. Enseña el dharma a cualquiera que quiera escuchar y también gestiona los funerales y el cementerio. </p>
    <p>Una vez al mes, realiza un "concierto en directo sutra-chanting de la noche a la mañana", donde canta una canción en monotono mientras mantiene el ritmo con un pez de madera. El evento atrae tanto a youkai como a los humanos. </p>
      </descripcion>
      <audio>audio/byakuren.mp3</audio>
      <tituloAudio>Emotional Skyscraper ~ Cosmic Mind</tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/14/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/sukuna.png</imagen>
    
    <perfil id="sukuna" alias="Descendiente de los Inchlings" rareza="excepcional">
      <nombre>Shinmyoumaru Sukuna</nombre>
      <especie>Inchling</especie>
      <poder>Uso del "Martillo de los milagros"</poder>
      <localizacion>Castillo de la aguja brillante</localizacion>
      <descripcion>
      <p>Es descendiente de Issun-Boushi, un legendario cazador de Oni que logró obtener de ellos un tesoro llamado el Martillo de los milagros. </p>
      <p> Uno de sus descendientes lo decidió usar para vivir del lujo, deseando un gran castillo y el poder gobernar sobre la gente. En ese momento, apareció el Castillo de la Aguja brillante, y la energía del Martillo de los Milagros se agotó. Poco después, el precio del uso de tal poder empezó a manifestarse, el castillo se puso al revés y acto seguido descendieron a Gensokyo.</p>
      <p>Actualmente reside en el Castillo de la aguja brillante, ha pasado mucho tiempo desde entonces y la gente de su raza que conocían ese pasado ya ha fallecido.</p>
     
      </descripcion>
      <audio>audio/sukuna.mp3</audio>
      <tituloAudio>Inchlings of the Shining Needle ~ Little Princess</tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/10/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/kanako.png</imagen>
    
    <perfil id="Kanako" alias="Avatar de las montañas y lagos" rareza="Atipica">
      <nombre>Kanako Yasaka</nombre>
      <especie>Diosa del viento y de la lluvia</especie>
      <poder>Creación del Quián (Poder celestial)</poder>
      <localizacion>Santuario Moriya</localizacion>
      <descripcion>
      <p>Una de los diosas de Yamato, se hizo cargo del reino gobernado por la diosa nativa Suwako Moriya sosteniendo una delgada vid que oxidaba  inmediatamente todo el armamento de hierro de Suwako. Sin embargo, a los habitantes del reino de Suwako les resultó difícil aceptar su nueva deidad. Con el fin de consolidar su reino recién descubierto, tomó prestados los poderes de Suwako.</p>
        <p>Sin embargo, a medida que pasaba el tiempo los humanos finalmente comenzaron a no creer en el concepto de eternidad, que Kanako en parte representaba. Se hicieron más fuertes e inventaron formas de sortear los problemas agrícolas que planteaba la fuerte lluvia y el viento. A medida que su creencia en la ciencia y la información creció, su fe en dioses como Kanako menguaba, y así hizo su poder. </p>
        <p>Decidió que lo más apropiado sería abandonar el mundo humano y reunir la fe en Gensokyo. Terminó funcionando bastante bien, y comenzó a ser adorada como la deidad de la montaña Youkai.  </p>
      </descripcion>
      <audio>audio/kanako.mp3</audio>
      <tituloAudio>The Venerable Ancient Battlefield ~ Suwa Foughten Field</tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/7/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/youmu.png</imagen>
    
    <perfil id="Yuyuko" alias="Fantasma del idilio" rareza="legendaria">
      <nombre>Yuyuko Saigyouji</nombre>
      <especie>Fantasma</especie>
      <poder>Manipulación de la muerte</poder>
      <localizacion>Hakugyokurou (Inframundo)</localizacion>
      <descripcion>
        <p>Al principio, Yuyuko sólo poseía la habilidad de manipular las almas difuntas. Inconscientemente, ese poder se fortaleció y eventualmente poseyó la habilidad de tentar a otros a su muerte. Aterrorizada por su propia habilidad, se suicidó.  </p>
        <p>La razón por la que Yuyuko no puede reencarnar ni desaparecer es por el sello en el Saigyou Ayakashi. Una vez que se rompa la frontera, el tiempo que se congeló continuará fluyendo, resultando en su muerte de nuevo. Revivir el cadáver destruirá el fantasma de Yuyuko, así que no es de extrañar que el casi éxito del avivamiento terminara en un fracaso inevitable.  </p>
      <p> Después de todo, Yuyuko no es capaz de manipular nada más que la muerte.</p>
      </descripcion>
      <audio>audio/yuyuko.mp3</audio>
      <tituloAudio>Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life</tituloAudio>
    </perfil>
    
    <perfil id="Youmu" alias="Jardinera mitad humana" rareza="considerable">
      <nombre>Youmu Kompaku</nombre>
      <especie>Mitad humana - Mitad Fantasma</especie>
      <poder>Técnicas de espada</poder>
      <localizacion>Hakugyokurou (Inframundo)</localizacion>
      <descripcion>
        <p>Una jardinera que trabaja y vive en Hakugyokurou. Es mitad humana y mitad fantasma, mitad muerta y mitad viva.</p>
        <p>Ni siquiera ella misma está segura de si está viva o no. A pesar de que tiene una esperanza de vida más larga que la de los humanos, parece que puede experimentar la muerte. Sus espadas fueron diseñadas principalmente contra seres espirituales, pero parecen funcionar también contra los seres vivos.  </p>
      <p> Su katana se llama Roukanken, forjada por un yokai y con la capacidad de matar a diez fantasmas de un solo tajo, mientras que su wakizashi se llama Hakurouken y es una herencia de la familia Konpaku.</p>
      </descripcion>
      <audio>audio/youmu.mp3</audio>
      <tituloAudio>Hiroari Shoots a Strange Bird ~ Till When?</tituloAudio>
    </perfil>
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/9/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/eiki.png</imagen>
    
    <perfil id="Eiki" alias="Jueza suprema del paraíso" rareza="Atipica">
      <nombre>Eiki Shiki, Yamaxanadu</nombre>
      <especie>Yama</especie>
      <poder>Juzgar cualquier cosa</poder>
      <localizacion>Higan</localizacion>
      <descripcion>
        <p>El Yama que juzga a las personas después de morir, Eiki es imparcial con cualquiera ya sea humano o youkai y decide si van al Cielo, al Infierno, al Inframundo, o si son reencarnados.  </p>
        <p>A diferencia de los humanos, tiene un criterio de lo correcto y lo incorrecto en su propia mente. Su sentencia no puede ser anulada por el fallecido. Su criterio es bastante complicado, y la gravedad de los crímenes factoría en todo, desde por qué se les ocurrió hasta la historia personal de los involucrados. </p>
      <p>Ya sea porque tiene la costumbre de sermonear o porque realmente quiere que otros cambien para mejor, se ha vuelto muy conocida en Gensokyo por dar lecciones a cualquiera y a todos sobre sus defectos. Las almas de los muertos son traídas a ella por Komachi Onozuka, quien los transporta sobre el río Sanzu hasta Higan, aunque no todas las almas consiguen recorrer todo el camino sin estar cansadas del viaje o ser extinguida directamente por Komachi.</p>
      </descripcion>
      <audio>audio/eiki.mp3</audio>
      <tituloAudio>Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years </tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/16/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/okina.png</imagen>
    
    <perfil id="okina" alias="Diosa absolutamente secreta" rareza="legendaria">
      <nombre>Okina Matara</nombre>
      <especie>Diosa secreta</especie>
      <poder>Crear "Puertas traseras" donde quiera</poder>
      <localizacion>Tierra de la puerta trasera</localizacion>
      <descripcion>
      <p>Una diosa escondida que acecha detrás de todas las cosas jamás creadas. Nadie sabe cuál es su verdadera naturaleza, es la última diosa secreta, cuya verdadera forma nunca debe ser vista, oída o hablada.</p>
      <p> Posee una amplia gama de caras y nombres públicos... la diosa madre de la Tierra, la diosa de noh, la diosa de las estrellas, la diosa de cría de gusanos de seda, la diosa de los pueblos discriminados, etcétera.</p>
      <p>No muestra misericordia de aquellos que actúan groseramente con ella, y concede bendiciones a aquellos que la tratan con reverencia. </p>
      <p>Es una de las sabias que creó el Gensokyo y se encarga de protegerlo, aunque sus tareas más insignificantes suelen ser confiadas a sus dos sirvientes douji, Satono y Mai.  </p>
     
      </descripcion>
      <audio>audio/okina.opus</audio>
      <tituloAudio>The Concealed Four Seasons</tituloAudio>
   </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/11/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/okuu.png</imagen>
    
    <perfil id="Okuu" alias="Problemática divina" rareza="Peligrosa">
      <nombre>Utsuho Reiuji</nombre>
      <especie>Cuervo del infierno</especie>
      <poder>Manipular la fusión nuclear</poder>
      <localizacion>Antiguo infierno de los fuegos ardientes</localizacion>
      <descripcion>
      <p>Se encarga de controlar la temperatura del infierno de los fuegos ardientes, si las llamas se vuelven demasiado calientes, abre las compuertas externas y si las llamas se debilitan demasiado, arroja a más cadáveres a las llamas.</p>
        <p> En su interior reside el poder de Yatagarasu, el cuervo divino de tres patas.  </p>
        <p> Posee tres artefactos o "patas" con las que se dice que puede controlar la energía definitiva, en su pierna izquierda la fisión, en la derecha la fusión, y en su brazo controla ambas energías con un cañón llamado "La tercera pata"</p>
      </descripcion>
      <audio>audio/okuu.mp3</audio>
      <tituloAudio>Solar Sect of Mystic Wisdom ~ Nuclear Fusion</tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>

=== VioletKimera/Examen_Marcas/13/personajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes SYSTEM "personajes.dtd">
<?xml-stylesheet type="text/xsl" href="estilos.xsl"?>

<personajes>
  <personaje id="DobleFicha" alias="Fusión" rareza="raro">
    <imagen>img/miko.png</imagen>
    
    <perfil id="miko" alias="Taoista Shoutoku" rareza="rara">
      <nombre>Toyosatomimi no Miko</nombre>
      <especie>Santa, Hermitaña</especie>
      <poder>Escuchar conversaciones de diez personas a la vez</poder>
      <localizacion>El gran mausoleo</localizacion>
      <descripcion>
      <p>Los rumores sobre ella se extendían por toda la tierra, ganando una enorme popularidad como santa. </p>
      <p>"La tierra no ha cambiado a partir de la era de los dioses, y los mares todavía están llenos hasta el borde.
¿Por qué los humanos deben ser obligados a aceptar la muerte?" Insatisfecha con su destino de que como humana acabaría muriendo, empezó sus investigaciones con el Taoismo.</p>
        <p>El taoísmo era esencialmente la adoración de la naturaleza, y al convertirse en uno con la naturaleza podía otorgar la inmortalidad a sus seguidores. 
    Extendió el budismo por todo el país, mientras que en las sombras, avanzaba con sus propios experimentos del taoísmo.
Como resultado, obtuvo habilidades sobrehumanas. </p>
    <p>Pensando que no podía esperar lo suficiente con el estado en el que estaba su cuerpo, decidió convertirse en un shikaisen. Esta era una técnica secreta en la que moriría  y sería resucitada después. </p>
    <p>Había planeado despertar cuando la nación se sintiese limitada por sus preceptos budistas y sintiese la necesidad de tener un santo. Pero los cálculos salieron mal y la nación estuvo controlada por el budismo por más de mil años. </p>
      </descripcion>
      <audio>audio/miko.mp3</audio>
      <tituloAudio>Shoutoku Legend ~ True Administrator</tituloAudio>
    </perfil>
    
    
    
  </personaje>
</personajes>
